runtime: nodejs20

instance_class: F1

env_variables:
  FRONTEND_SERVER_URL:
  EMAIL_SERVICE:
  EMAIL_USERNAME:
  EMAIL_PASSWORD:
  JWT_SECRET:
  JWT_VERIFICATION_SECRET:
  JWT_TTL:
  DB_HOST:
  DB_USERNAME:
  DB_PASSWORD:

handlers:
  - url: /.*
    secure: always
    script: auto

automatic_scaling:
  max_instances: 5
  min_instances: 1
