FROM node:20.12-alpine

RUN apk update && apk upgrade && apk add dumb-init

ENV NODE_ENV production
WORKDIR /usr/src/server

RUN addgroup --system hbf-group
RUN adduser --system hbf-user --ingroup hbf-group
COPY --chown=hbf-user:hbf-group . .

RUN npm ci --omit=dev
RUN chown -R hbf-user:hbf-group /usr/src/server
USER hbf-user

ARG PORT
ENV PORT=${PORT}

ARG EMAIL_SERVICE
ENV EMAIL_SERVICE=${EMAIL_SERVICE}
ARG EMAIL_USERNAME
ENV EMAIL_USERNAME=${EMAIL_USERNAME}
ARG EMAIL_PASSWORD
ENV EMAIL_PASSWORD=${EMAIL_PASSWORD}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}
ARG JWT_VERIFICATION_SECRET
ENV JWT_VERIFICATION_SECRET=${JWT_VERIFICATION_SECRET}
ARG JWT_TTL
ENV JWT_TTL=${JWT_TTL}

ARG FRONTEND_SERVER_URL
ENV FRONTEND_SERVER_URL=${FRONTEND_SERVER_URL}

ARG DB_HOST
ENV DB_HOST=${DB_HOST}
ARG DB_USERNAME
ENV DB_USERNAME=${DB_USERNAME}
ARG DB_PASSWORD
ENV DB_PASSWORD=${DB_PASSWORD}

CMD ["dumb-init", "npm", "run", "prod"]