name: Deploy to Google App Engine

on:
  push:
    branches: [ "backend/prod" ]

env:
  PROJECT_ID: hospital-bed-finder
  REGION: us-west1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Deploy to Google App Engine
        id: deploy
        uses: 'google-github-actions/deploy-appengine@v2'
        with:
          env_vars: |-
            FRONTEND_SERVER_URL=${{ env.FRONTEND_SERVER_URL }}
            PORT=${{ env.PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EMAIL_SERVICE=${{ secrets.EMAIL_SERVICE }}
            EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_VERIFICATION_SECRET=${{ secrets.JWT_VERIFICATION_SECRET }}
            JWT_TTL=${{ secrets.JWT_TTL }}
          flags: "--log-http"
        
      - name: 'test'
        run: 'curl "${{ steps.deploy.outputs.version_url }}"'
